@FabuRobotics.AIAgent_HostAddress = http://localhost:5116
@OrderId = b7dc6819-2109-4b11-9d89-507dbd9493cd

### Hola
GET {{FabuRobotics.AIAgent_HostAddress}}/agent?message=hola%20quien%20eres
Accept: application/json

### FB-01

GET {{FabuRobotics.AIAgent_HostAddress}}/agent?message=dime%20si%20podemos%20ensamblar%20el%20FB-01
Accept: application/json

### FB-02

GET {{FabuRobotics.AIAgent_HostAddress}}/agent?message=dime%20si%20podemos%20ensamblar%20el%20FB-02
Accept: application/json

### FB-03

GET {{FabuRobotics.AIAgent_HostAddress}}/agent?message=dime%20si%20podemos%20ensamblar%20el%20FB-03
Accept: application/json


